server:
  port: 5071
 
spring:
  profiles:
    active: list1
# ==============================================================
# = Propriet√† Fonte Dati PostgreSQL
# ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
gestuser:
  password: MagicaBula_2018
  srvUrl: http://localhost:8019/api/utenti/cerca/userId/
  userId: Admin
sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: 123_Stella

